### ISSUE TITLE
Implement the automatic loading of OCR models

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#16]
# Task Title

Implement the automatic loading of OCR models

## Task Description

When the user selects (click) on the language on the main page then the corresponding ocr model should be automatically loaded. following that when the user clicks the image the OCR inference should be lightning fast.

## Steps to complete

- [x] NLTM-IIITH/ocr-api#2
- [x] #15 
- [x] Make a call to the ocr load model endpoint when user selects the language.
- [x] All the calls to the ocr api endpoints for images should have query param preloaded=True
