### ISSUE TITLE
Add more images for rest of 12 Indian languages

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#17]
# Task Title

Add more images for rest of 12 Indian languages

## Task Description

Right now, aside from hindi (which has around 20 images) rest of the 12 Indian languages only have a single image to show for.
Add atleast 20 more images for each language

## Steps to complete

- [x] Add 5 images from consortium dataset for all the languages.
- [x] Add 5 images from NDLI dataset for all the languages.
- [x] Request Aradhana to select 10 images from the dropbox link shared.
