### ISSUE TITLE
Store the output of the layout parser for image inside a folder

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#3]
# Task Title

store the output of the layout parser for the image inside a folder location

## Task Description

when we get the output of backend api for some image in the frontend, store the layout parser part of the json output inside a separate folder so that highlighting flaks api can access this layout parser output directly.
preferably we can store the layout parser outputs at location: **/static/layouts/\<language>/\<number>.json**

## Steps to complete

- [x] #2 
- [x] segregate all the dummy static images into separate folders according to their languages
- [x] remove the hard-coded path to the image files and add the path in a separate config.py file
- [x] create separate folders to store the pageocr json output received from backend API
- [x] update the [page](https://github.com/NLTM-IIITH/pageocr/blob/2b4de52c4659b2932efb9c0870786969fb99211b/frontend/app.py#L24) function to save the json response received at the appropriate location
