### ISSUE TITLE
When selecting the text the corresponding word area is highlighted

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#4]
# Task Title

When selecting the text the corresponding word area is highlighted

## Task Description

In the page.html if the user selects a patch of words from the right column, then the bounding boxes to those words are drawn in the left image column.
this can help the user in visualising where a particular word is present in the image.

## Linked Issues

Issues that have to be closed before starting the work on this issue: #3 #2 

## Steps to complete

- [x] #2 
- [x] #3 
- [x] construct a JS function that is triggered every time the user selects the words from the right column.
- [x] send an ajax call to the flask frontend server containing the details of the words/lines selected by user and get the final bounding box coordinates that needs to be drawn into the image.
- [x] after getting the coordinates in js, figure out a way to draw this box onto the image.
