### ISSUE TITLE
Optimize the time taken to get the page ocr output

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#7]
# Task Title

Optimize the time taken to get the page ocr output

## Task Description

In the frontend, the pageocr API takes around 30-40 seconds to get the output for one page.
this is not sufficient, we have to improve the time taken to get the final result of the pageocr to preferably less then 10 seconds.

## Linked Issues

- [x] NLTM-IIITH/ocr-api#2
- [x] NLTM-IIITH/layout-parser#5
- [ ] check the feasibility of getting the base64 string of the opencv image object directly without saving the image to disk
