### ISSUE TITLE
Modify the application to include rest of the 13 indian languages

### ISSUE THREAD

**Issue by krishna0512** [NLTM-IIITH/pageocr#9]
# Task Title

Modify the application to include rest of the 13 Indian languages

## Task Description

right now, the application only works for one language (hindi). modify both the frontend and backend to add support for multiple languages

## Steps to complete

- [x] #3 
- [x] Update the backend API to also take the language alongside the uploaded image as an input
- [x] give the language argument alongside the image when calling the backend API from frontend
- [x] Use [bootstrap accordion](https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example) to display images from different languages in the html frontend.
- [x] Add some of the pages of rest of the languages from varied sources like **consortium**, **ndli**, **dropbox collection**, etc.
